#!/usr/bin/perl -w

use strict;
use lib '/home/msingleton/lib/';
use PostData;
use FileHandle;
use MVS::Utils;
use Getopt::Std;
use List::MoreUtils qw/uniq/;
use vars qw($opt_i $opt_d $opt_a $opt_b);
my $cmd = $0.' '.join(' ', @ARGV);
getopts('i:d:a:b:');
$| =1;


my $usage = "\n\n".
    'USAGE'."\n\n".
    '-i    <dbsnp.gvf directory>'."\n".
    '-d    <OMIM prefix>'."\n".
    '-a/-b <in.gvf/out.gvf>'."\n".

    ''."\n".

    "\n\n";

die $usage unless args_ok();

##-------------------Variables-------------------##
my @CHROM = qw(chr1 chr2 chr3 chr4 chr5 chr6 chr7
	       chr8 chr9 chr10 chr11 chr12 chr13
	       chr14 chr15 chr16 chr17 chr18 chr19
	       chr20 chr21 chr22 chrX chrY chrMT);
my %GVF;
my %OMIM;


##---------------------Body----------------------##
my @FILES = get_files($opt_i);
foreach(@CHROM){
    my $chr = $_;
    #next unless $chr eq 'chr10';
    print STDERR "Getting variants for $chr \n";
    my $max = 0;
    my $min = 1000000000000;
    foreach(@FILES){
	my ($high, $low) = get_locations($_, $chr);
	$max = $high unless $max > $high;
	$min = $low unless $min < $low;
    }
    next unless (keys %GVF) > 0;
    get_OMIM($opt_d, $chr, $max, $min);
    foreach(@FILES){
	print STDERR "\t\tAnnotating $_\n";
	print_annotations($_, $chr);
    }
    %GVF = ();
    %OMIM = ();
}
foreach(@FILES){
    $_ =~ s/$opt_a/$opt_b/;
    my $total_var = `cat $_ | grep -v '#' | wc -l`;
    chomp $total_var;
    my $annotated = `cat $_ | grep -v '#' | grep OMIM | wc -l`;
    chomp $annotated;
    print STDERR "$_ Annotated $annotated of $total_var variants\n";
}

##------------------PostData---------------------##

##-----------------------------------------------##


##---------------------SUBS----------------------##
##-----------------------------------------------##
sub add_pragmas{
    my $line = shift;
    my $file = shift;
    return $line unless $line =~ /attribute-method/;
    my $add = $cmd;
    $add =~ s/$opt_i/$file/;
    $line .= 'Annotation_OMIM='.$add.';';
    return $line;
}
##-----------------------------------------------##
sub print_annotations{
    my $file = shift;
    my $filter = shift;
    my $outfile = $file;
    $outfile =~ s/$opt_a/$opt_b/;
    my $in = new FileHandle;
    my $out = new FileHandle;
    $in -> open($file);
    $out -> open(">> $outfile");
    while(defined(my $line = <$in>)){
	chomp $line;
	if($line =~ /\#/){
	    next unless $filter eq 'chr1';
	    $line = add_pragmas($line, $file);
	    print $out $line."\n";
	    next;
	}
	next if length($line) == 0;
        my ($chr, $source, $type, $start, $stop, $five, $strand, $seven, $info) = split(/\t/, $line);
	next unless $chr eq $filter;
	if(defined $OMIM{$start}){
	    my $id = $OMIM{$start}{id};
	    if($id =~ /\,/){
		$id =~ s/,/,OMIM:/g;
	    }
	    my @split = split(/\;/, $info);
	    my @new_info;
	    if($info =~ /Dbxref/){
		foreach(@split){
		    next unless length($_) > 0;
		    $_ .= ',OMIM:'.$id if $_ =~ /Dbxref/;
		    push(@new_info, $_);
		}
	    }else{
		foreach(@split){
		    next unless length($_) > 0;
		    push(@new_info, $_);
		    push(@new_info, 'Dbxref=OMIM:'.$id);
		}
	    }
	    my $add = join(';', uniq(@new_info));
	    my $new_line = join("\t", $chr, $source, $type, $start, $stop, $five, $strand, $seven, $add);
	    print $out $new_line."\n";
	}else{
	    print $out $line."\n";
	}
    }
}
##-----------------------------------------------##
sub get_OMIM{
    my $file = shift;
    my $filter = shift;
    my $max = shift;
    my $min = shift;
    print STDERR "\tGetting OMIM for $filter\n";
    $file .= $filter.'.gvf';
    my $fh = new FileHandle;
    $fh -> open($file);
    while(defined(my $line = <$fh>)){
	chomp $line;
	my ($chr, $source, $type, $start, $stop, $five, $strand, $seven, $info) = split(/\t/, $line);
	next if $start < $min;
	next unless defined $GVF{$start};
	last if $start > $max;
	my $check = check_type($start, $type);
	next unless $check > 0;
	my $id = $info;
	$id =~ s/ID=//;
	if(defined($OMIM{$start}) && $OMIM{$start}{id} ne $id ){
	    $OMIM{$start}{id} .= ','.$id;
	}else{
	    $OMIM{$start}{id} = $id;
	}
    }
}
##-----------------------------------------------##
sub check_type{
    my $start = shift;
    my $type = shift;
    my $ref = $GVF{$start};
    my $result = 0;
    if($type eq 'SNV'){
	$result++ if $ref =~ /SNV/;
    }else{
	$result++ if $ref =~ /NUCLEOTIDE/;
    }
    if($type eq 'unknown' && $result == 0){
	$result++;
    }
    return $result;
}
##-----------------------------------------------##
sub get_locations{
    my $file = shift;
    my $filter = shift;
    my $fh = new FileHandle;
    $fh -> open($file);
    my $max = 0;
    my $min = 1000000000000;
    while(defined(my $line = <$fh>)){
	chomp $line;
	next if $line =~ /\#/;
	next if length($line) == 0;
	my ($chr, $source, $type, $start, $stop, $quality, $strand, $seven, $info) = split(/\t/, $line);
	next unless $filter eq $chr;
	$GVF{$start} .= $type.';';
	$max = $start unless $max > $start;
	$min = $start unless $min < $start;
    }
    return ($max, $min);;
}
##-----------------------------------------------##
sub get_files{
    my $dir = shift;
    opendir(DIR, $dir);
    my @files = readdir(DIR);
    my @gvf;
    foreach(@files){
	push(@gvf, $dir.$_) if $_ =~ /$opt_a/;
    }
    return @gvf;
}
##-----------------------------------------------##
##-----------------------------------------------##
sub args_ok {
    return 0 unless $opt_i && $opt_d && $opt_a && $opt_b;
    return 1;
}
